// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1FoGD_GKawXYULcT8Yz0o_Ra_8WXOxfQ',
    appId: '1:227314197376:web:a4b60ff48291375b8f5765',
    messagingSenderId: '227314197376',
    projectId: 'con-cidadania',
    authDomain: 'con-cidadania.firebaseapp.com',
    storageBucket: 'con-cidadania.firebasestorage.app',
    measurementId: 'G-KZHE7W4L1C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD57rcWrGfITPz0vgG-ICUt9QHpT5o3JT4',
    appId: '1:227314197376:android:cec2f2713f1104a18f5765',
    messagingSenderId: '227314197376',
    projectId: 'con-cidadania',
    storageBucket: 'con-cidadania.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtnZr2QRH_l5o42-alP6xU5C5oykomYxE',
    appId: '1:227314197376:ios:dc8cfea233da5d478f5765',
    messagingSenderId: '227314197376',
    projectId: 'con-cidadania',
    storageBucket: 'con-cidadania.firebasestorage.app',
    iosBundleId: 'com.example.conCidadania',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtnZr2QRH_l5o42-alP6xU5C5oykomYxE',
    appId: '1:227314197376:ios:dc8cfea233da5d478f5765',
    messagingSenderId: '227314197376',
    projectId: 'con-cidadania',
    storageBucket: 'con-cidadania.firebasestorage.app',
    iosBundleId: 'com.example.conCidadania',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1FoGD_GKawXYULcT8Yz0o_Ra_8WXOxfQ',
    appId: '1:227314197376:web:91b331fac9b2d6b38f5765',
    messagingSenderId: '227314197376',
    projectId: 'con-cidadania',
    authDomain: 'con-cidadania.firebaseapp.com',
    storageBucket: 'con-cidadania.firebasestorage.app',
    measurementId: 'G-NNZXKJKDP2',
  );

}